server:
  port: 3000

spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver # 사용할 JDBC 드라이버 클래스 지정
    url: jdbc:oracle:thin:@${db.host}:${db.port}:XE # 데이터베이스 연결 URL 지정
    username: ${db.username} # 데이터베이스에 접속하기 위한 사용자 이름과 비밀번호 설정
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: create

  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true


  # 정적 자원(CSS, JS, 이미지 등)이 위치한 디렉토리 지정
  web:
    resources:
      static-locations: file:src/main/resources/static/

# 로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
